import { UserAuthContextProvider } from "@/context/UserAuthContext";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Toaster closeButton={true} position="bottom-right" />
      <link rel="icon" type="image/x-icon" href="/assets/images/logo.svg" />
      <UserAuthContextProvider>
        <body className={inter.className}>{children}</body>
      </UserAuthContextProvider>
    </html>
  );
}
